application/auth.py
"""Routes for user authentication."""
from flask import redirect, render_template, flash, Blueprint, request, url_for
from flask_login import login_required, logout_user, current_user, login_user
from flask import current_app as app
from werkzeug.security import generate_password_hash
from .assets import compile_auth_assets
from .forms import LoginForm, SignupForm, CreatePlantForm, DeletePlantForm
from .models import db, User
from .import login_manager
from .models import Plants, Sensors, SensorInfo
from sqlalchemy.sql import select


# Blueprint Configuration
auth_bp = Blueprint('auth_bp', __name__,
                    template_folder='templates',
                    static_folder='static')
compile_auth_assets(app)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login_page():
    """User login page."""
    # Bypass Login screen if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for('auth_bp.plantDashboardAuth'))
        #was main_bp.dashboard
    login_form = LoginForm(request.form)
    # POST: Create user and redirect them to the app
    if request.method == 'POST':
        if login_form.validate():
            # Get Form Fields
            email = request.form.get('email')
            password = request.form.get('password')
            # Validate Login Attempt
            user = User.query.filter_by(email=email).first()
            if user:
                if user.check_password(password=password):
                    login_user(user)
                    next = request.args.get('next')
                    return redirect(next or url_for('auth_bp.plantDashboardAuth')) #was main_bp.dashboard
        flash('Invalid username/password combination')
        return redirect(url_for('auth_bp.login_page'))
    # GET: Serve Log-in page
    return render_template('login.html',
                           form=LoginForm(),
                           title='Log in | Project GardenApp',
                           template='login-page',
                           body="Log in with your User account.")


@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup_page():
    """User sign-up page."""

    signup_form = SignupForm(request.form)

    if request.method == 'POST':
        if signup_form.validate():
            # Get Form Fields
            name = request.form.get('name')
            email = request.form.get('email')
            password = request.form.get('password')
            website = request.form.get('website')
            existing_user = User.query.filter_by(email=email).first()
            if existing_user is None:
                user = User(name=name,
                            email=email,
                            password=generate_password_hash(password, method='sha256'),
                            website=website)
                db.session.add(user)
                db.session.commit()
                login_user(user)
                return redirect(url_for('main_bp.dashboard'))
            flash('A user already exists with that email address.')
            return redirect(url_for('auth_bp.signup_page'))
    # GET: Serve Sign-up page
    return render_template('/signup.html',
                           title='Create an Account | Project GardenApp',
                           form=SignupForm(),
                           template='signup-page',
                           body="Sign up for a user account.")


@auth_bp.route('/plants', methods=['GET', 'POST'])
@login_required
def plantDashboardAuth():
    """Provide plant dashboard"""

    plantListDisplay = Plants.query.filter_by(userID=current_user.id)
    #plantListDisplay = db.query(Plants).filter_by(userID=current_user.id)
    create_plant = CreatePlantForm(request.form)
    delete_plant = DeletePlantForm(request.form)

    if request.method == 'POST':
        if delete_plant.validate():
            userinput = request.form.get('plantName1')
            userID = current_user.id

            #obj = Plants.query.filter_by(plantName=plantName1)
            #obj = db.session.execute('SELECT userID, plantName, plantType, plantThirst, sensorID FROM plants WHERE plantName =  \'%s\'' % plantName1)
            #userinput = "Delete Me 1"

            #submit data to DB
            #db.session.delete(obj)
            flash('TESTING !23')
            flash(userinput)
            app.logger.info(userinput)
            db.session.query(Plants).filter(plantName=userinput).delete()
            db.session.commit()
            flash('Your plant was deleted!')

            #reload the page
            return redirect(url_for('auth_bp.plantDashboardAuth'))

        if create_plant.validate():
            plantName = request.form.get('plantName')
            plantType = request.form.get('plantType')
            plantThirst = request.form.get('plantThirst')
            sensorID = request.form.get('sensorID')

            #create plant object
            plant = Plants(userID=current_user.id,
                           plantName=plantName,
                           plantType=plantType,
                           plantThirst=plantThirst,
                           sensorID=sensorID)

            #submit data to DB
            db.session.add(plant)
            db.session.commit()
            flash('Your plant was added!')

            #reload the page
            return redirect(url_for('auth_bp.plantDashboardAuth'))



    return render_template('plants.html',
                           title='Plant Dashboard | Project GardenApp',
                           template='dashboard-template',
                           current_user=current_user,
                           form=CreatePlantForm(),
                           plants=plantListDisplay,
                           body="",
                           userID=(current_user.id))





@auth_bp.route('/plantinfo', methods=['GET'])
@login_required
def notificationList():
    """Notification and Plant Setting Page"""

    query1 = db.session.query(Plants, SensorInfo).outerjoin(SensorInfo, Plants.sensorID == SensorInfo.sensorID).all()

    query2 = db.session.execute('SELECT p.sensorID, p.plantName, s.moistRead, s.sensorTime FROM plants p, sensorInfo s WHERE p.sensorID = s.sensorID ORDER BY s.sensorTime DESC LIMIT 5;')

    return render_template('plantinfo.html',
                           title='Sensor Info | Project GardenApp',
                           template='dashboard-template',
                           current_user=current_user,
                           body="Moisture reading is displayed at each time a reading was taken.",
                           display=query2)


@auth_bp.route("/logout")
@login_required
def logout_page():
    """User log-out logic."""
    logout_user()
    return redirect(url_for('auth_bp.login_page'))


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login_page'))

application/templates/dashboard.html
{% extends "layout.html" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
    <h1>{{body}}</h1>

    {% if current_user.is_authenticated %}
    <p>Welcome {{ current_user.name }}!</p>
    <a href="{{ url_for('auth_bp.logout_page') }}">Log out</a>
  {% endif %}
{% endblock %}

application/templates/layout.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% include 'meta.html' %}
    {% block pagestyles %}{% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet">
      <title></title>
  </head>
<style>
    .navbar-default {
        background-color: rgba(255, 255, 255, 0.8);
        padding:25px 0;
    }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Project GardenApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
 <!-- LINK FOR HOME PAGE -->
            <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('main_bp.dashboard') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <!-- LINK FOR PLANTS PAGE -->
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth_bp.plantDashboardAuth') }}">Plants</a>
            </li>
            <!-- LINK FOR PLANTS PAGE -->
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth_bp.notificationList') }}">Plant Sensor Info</a>
            </li>
            <!-- LINK FOR SIGNUP PAGE -->
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth_bp.signup_page') }}">Sign Up</a>
            </li>
            <!-- LINK FOR PLANTS PAGE -->
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth_bp.logout_page') }}">Logout</a>
      </li>
    </ul>
  </div>
</nav>


  <body class="{{template}}">

      {% block content %}{% endblock %}


    <!-- Scripts -->
    {% include 'scripts.html' %}

    {% block additionalscripts %}{% endblock %}

  </body>

</html>

application/templates/login.html
{% extends "layout.html" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}



{% block content %}

<!-- <style>
    body.login-page {
        background-image: url(/static/dist/img/daisies.png);
        background-size: cover;
        background-position-x:center;
    }
    </style> -->

  <div class="formwrapper">
    <form method=post>
      <div class="logo">
        <img src="{{ url_for('static', filename='dist/img/flavicon.png') }}">
      </div>
      {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
      {% endfor %}
      <h1>Log In</h1>
      <div class="email">
         {{ form.email.label }}
         {{ form.email(placeholder='youremail@example.com') }}
         {% if form.email.errors %}
           <ul class="errors">
             {% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}
           </ul>
         {% endif %}
      </div>
      <div class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </div>
      <div class="submitbutton">
        <input id="submit" type="submit" value="Submit">
      </div>
      <div class="loginsignup">
        <span>Don't have an account? <a href="{{ url_for('auth_bp.signup_page') }}">Sign up.</a><span>
        </div>
    </form>
  </div>
{% endblock %}

application/templates/meta.html
{% block meta %}
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible"
        content="IE=edge" />
  <title>{{title}}</title>
  <meta name="HandheldFriendly"
        content="True" />
<meta name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#5eb9d7" />
  <link rel="shortcut icon" href="{{ url_for('static', filename='dist/img/favicon.png') }}" type="image/x-icon"/>
{% endblock %}

application/templates/plantinfo.html
{% extends "layout.html" %}

{% block pagestyles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
{% endblock %}

{% block content %}

<!-- <style>
    body {
        background-image: url(/static/dist/img/purpleFlowers.png);
        background-size: cover;
        background-position-x:center;
    }
        h1 {color:white;}
        li {color:rebeccapurple}
    .infoList {
        background-color: rgba(255, 255, 255, 0.5);
        padding:25px 0;
    }
</style> -->

<style>
.infoList {
	display: table;
	width: 100%;

}
.infoList > ul {
	display: table-row;
}
.infoList > ul:nth-child(2n) {
	background-color: #eee;
}
.infoList > ul > li {
	display: table-cell;
	padding: 6px 8px;
}

	.infoList > ul > li:nth-child(1) {
	}
</style>

{% if current_user.is_authenticated %}
    <p>Hi {{ current_user.name }}!</p>

<div class="container-fluid">
<div class="row">
    <div class="col">
    <h1>{{body}}</h1>
</div>
</div>
    <div class="row">
        <div class="col">
        <div class="infoList">
        <!-- lists our plants -->
        {% for list in display %}
            <ul>
                <li> {{ list.plantName }}</li>
                <li> {{ list.sensorID }}</li>
                <li>{{ list.sensorTime }} ----> {{ list.moistRead }}</li>
            </ul>
        {% endfor %}
        </div>
        </div>
    </div>
</div>

       <!-- <a href="{{ url_for('auth_bp.logout_page') }}">Log out</a> -->
    {% endif %}
{% endblock %}

application/templates/plants.html
{% extends "layout.html" %}

from sqlalchemy import create_engine

{% block pagestyles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
{% endblock %}

{% block content %}

<!-- <style>
    body {
        background-image: url(/static/dist/img/plantHeart.png);
        background-size: cover;
        background-position-x:center;
    }
    .plantList {
        background-color: rgba(255, 255, 255, 0.5);
        padding:25px 0;
    }
</style> -->

<style>
.plantList > ul {
	list-style: none;
	padding-left: 0;
}

	.plantList > ul > li:first-child {
		font-size: 1.5em;
		font-weight: 300;
	}

	.plantList > ul > li:nth-child(2) {
		text-transform: uppercase;
		font-size: 0.9em;
		color: #333;
	}

	.plantList > ul > li:nth-child(3) {
		font-size: 1.3em;
		font-weight: 600;
	}

	.plantList > ul > li:nth-child(4) {
		font-size: 0.7em;
		color: #999;
		font-style: italic;
	}

.thirst-1,
.thirst-2,
.thirst-3,
.thirst-4 {
	color: green;
}

.thirst-5,
.thirst-6,
.thirst-7 {
	color: orange;
}

.thirst-8,
.thirst-9 {
	color: red;
	animation: thirstDanger 1.0s infinite;
}

@keyframes thirstDanger {
	0% {
		opacity: 1.0
	}

	50% {
		opacity: 0.5
	}

	100% {
		opacity: 1.0
	}
}


.infoList {
	display: table;
	width: 100%;

}
.infoList > ul {
	display: table-row;
}
.infoList > ul:nth-child(2n) {
	background-color: #eee;
}
.infoList > ul > li {
	display: table-cell;
	padding: 6px 8px;
}

	.infoList > ul > li:nth-child(1) {
	}
</style>


    <!-- Beginning of container for Bootstrap -->
<div class="container">
    <div class="row">
        <div class="col">

       <!-- Title is created on auth.py -->
        <style>
            h1 {color:white;}
            p1 {color:white;}
        </style>
        <h1>{{title}}</h1>

        <!-- Lists the logged in user's name -->
        {% if current_user.is_authenticated %}
        <p1>Hi {{ current_user.name }}!</p1>


        <!-- <p>Your userID is {{ current_user.id }}.</p> -->
        </div>


        <div class="col">
            <p> {{ body }} </p>
        </div>
    </div>
        <div class="row">
            <div class="col">

            <div class="plantList">
            <!-- lists our plants -->
            {% for plant in plants %}
                <ul plantID="plants.id">
                    <li>{{ plant.plantName }}</li>
                    <li>{{ plant.plantType }}</li>
                    <li class="thirst-{{ plant.plantThirst }}">Thirst Level: {{ plant.plantThirst }}</li>
                    <li>Sensor ID: {{ plant.sensorID }}</li>
                <p>------------------------------------</p>
                </ul>
            {% endfor %}
            </div>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Delete a Plant
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete a Plant</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <!-- The start of our form to create a new plant -->
            <div class="formwrapper">
                <form method=post>
                    {% for message in get_flashed_messages() %}
                        <div class="alert alert-warning">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            {{ message }}
                        </div>
                    {% endfor %}
                    <h1>Delete Plant</h1>
                    <div class="plantName1">
                        {{ form.plantName(placeholder='Kitchen Window Cactus') }}
                    <p>Delete a plant by typing the name and pressing submit.</p>
                        {% if form.plantName.errors %}
                            <ul class="errors">
                                {% for error in form.plantName.errors %}<li>{{ error }}</li>{% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                    <div class="submitbutton">
                        <input id="delete" type="submit" value="Submit">
                    </div>
                </form>
            </div>
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>





            <div class="col">


            <!-- The start of our form to create a new plant -->
            <div class="formwrapper">
                <form method=post>
                    <div class="logo">
                        <img src="{{ url_for('static', filename='dist/img/flavicon.png') }}" class="img-fluid" alt="Responsive image" style="width: 50%; height: 50%">
                    </div>

                    {% for message in get_flashed_messages() %}
                        <div class="alert alert-warning">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            {{ message }}
                        </div>
                    {% endfor %}
                    <h1>Create Plant</h1>
                    <div class="plantName">
                        {{ form.plantName(placeholder='Kitchen Window Cactus') }}
                        {% if form.plantName.errors %}
                            <ul class="errors">
                                {% for error in form.plantName.errors %}<li>{{ error }}</li>{% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                    <div class="plantType">
                        {{ form.plantType(placeholder='Mini Prickly Pear') }}
                        {% if form.plantType.errors %}
                            <ul class="errors">
                                {% for error in form.plantType.errors %}<li>{{ error }}</li>{% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                    <div class="plantThirst">
                        {{ form.plantThirst(placeholder='1-10') }}
                        {% if form.plantThirst.errors %}
                            <ul class="errors">
                                {% for error in form.plantThirst.errors %}<li>{{ error }}</li>{% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                    <div class="sensorID">
                        {{ form.sensorID(placeholder='1-100') }}
                        {% if form.sensorID.errors %}
                            <ul class="errors">
                                {% for error in form.sensorID.errors %}<li>{{ error }}</li>{% endfor %}
                            </ul>
                        {% endif %}
                    </div>

                    <div class="submitbutton">
                        <input id="submit" type="submit" value="Submit">
                    </div>
                </form>
            </div>


            </div>




        </div>
  <!--  <div class="row">
        <div class="col">
        <a href="{{ url_for('auth_bp.logout_page') }}">Log out</a>
        </div>
    </div> -->
</div>
        {% endif %}
{% endblock %}

application/templates/scripts.html
 <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
         integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
         crossorigin="anonymous">
 </script>

 <script crossorigin="anonymous"
         integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
         src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js">

 </script>

 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
         crossorigin="anonymous">
 </script>

application/templates/signup.html
{% extends "layout.html" %}

{% block pagestyles %}
    <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
  <div class="formwrapper">
    <form method=post>
      <div class="logo">
        <img src="{{ url_for('static', filename='dist/img/logo.png') }}">
      </div>
      {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
      {% endfor %}
      <h1>Sign Up</h1>
      <div class="name">
        {{ form.name.label }}
        {{ form.name(placeholder='John Smith') }}
        {% if form.name.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </div>
      <div class="email">
        {{ form.email.label }}
        {{ form.email(placeholder='youremail@example.com') }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </div>
      <div class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.password.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </div>
      <div class="confirm">
        {{ form.confirm.label }}
        {{ form.confirm }}
        {% if form.confirm.errors %}
          <ul class="errors">
            {% for error in form.confirm.errors %}<li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </div>
      <div class="website">
        {{ form.website.label }}
        {{ form.website(placeholder='http://example.com') }}
      </div>
      <div class="submitbutton">
        <input id="submit" type="submit" value="Submit">
      </div>
    </form>
    <div class="loginsignup">
      <span>Already have an account? <a href="{{ url_for('auth_bp.login_page') }}">Log in.</a><span>
    </div>
  </div>
{% endblock %}